#pragma once
#include <raylib.h>

Sound GenerateFootstepSound();
Sound GeneratePhoneSlideSound();
Sound GenerateCashRegisterSound();
Sound GenerateDrivewayBellSound();
Sound GeneratePumpFlowSound();
Sound GenerateNozzleLatchSound();
Sound GenerateNozzleShutoffSound();
Sound GenerateFlashlightToggleSound();
Sound GenerateLightSwitchSound();
Sound GeneratePhoneTapSound();
Sound GenerateRadioStaticSound();
Sound GenerateWaterDripSound();
Sound GenerateChestOpenSound();
Sound GenerateShovelDigSound();
Sound GenerateCricketAmbience();
Sound GenerateWindAmbience();
Sound GenerateThunderSound();
Sound GenerateRainSound();
Sound GenerateMenuNavSound();
Sound GenerateMenuBoomSound();
Sound GenerateElectricSparkSound();
Sound GenerateJumpscareSound();
Sound GenerateGunshotSound();
Sound GenerateStoreFootstepSound();
Sound GenerateFoilSound();
Sound GenerateStepperMotorSound();
Sound GenerateATMKeyBeep();
Sound GenerateATMCardFeed();
Sound GenerateATMCardEject();
Sound GenerateATMCashDispense();
Sound GenerateATMCashRuffle();
